apiVersion: integration/v1
kind: Step
name: slack-step-message-send
tags:
  - communication
  - messaging
  - alerts
  - alerting
version: 1
summary: Send a message to a Slack channel
description: |
  This step sends a message to a Slack channel.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/slack-step-message-send
