apiVersion: integration/v1
kind: Step
name: get-member-id-by-email
tags:
  - collaboration
  - messaging
  - alerts
  - alerting
version: 1
summary: Get member id by email
description: |
  Retrieve Slack member ID provided a users email address.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/slack-step-get-member-id-by-email
schemas:
  spec:
    source: file
    file: spec.schema.json
  outputs: 
    $schema: 'http://json-schema.org/draft-07/schema#'
    type: object
    properties:
      memberID:
        type: string
    required: [memberID]
examples:
- summary: Get member ID by email
  content:
    apiVersion: v1
    kind: Step
    name: slack-get-member-id-by-email
    image: relaysh/slack-step-get-member-id-by-email
    spec:
      connection: !Connection { type: slack, name: my-slack-account}
      email: !Parameter email # Example: "foo@example.com"
